### ISSUE TITLE
Searching by empty string throws ArgumentNullException

### ISSUE THREAD

**Issue by siderisltd** [ninjanye/SearchExtensions#10]
Searching by empty string : 

            var resultsInTitles = this.repo
                                      .All()
                                      .Search(x => x.Title.ToLower())
                                      .Containing(query.ToLower())
                                      .ToRanked()
                                      .OrderByDescending(r => r.Hits);

If query is "" :
Actual -> Throws

Expected -> Return all results

**Comment by ninjanye** [comment]
Thanks for reading an issue @siderisltd. I'll fix this up in the next day or so

**Comment by Syl2020** [comment]
Hi John,
Please reopen this ticket.

If query is string.Empty  Expected -> Return all results.
In version 2.0.6149.33145 a empty string is manage such as a space and return only string containing a space not all results. 

Thx,
