### ISSUE TITLE
EF .Include(x => x.Something) not working when using SearchExtensions

### ISSUE THREAD

**Issue by aalho** [ninjanye/SearchExtensions#11]
Hi!

Lets say that you have a customers which have 0 to n orders.

You would construct the query using EF something like this:

query = dbContext.Customers.AsQueryable();
.
.
.
query = query.Search(customer => customer.Firstname).ContainingAll(filter.FirstNames);
.
.
.

And then lastly you would add the include for each customer's orders like so:
query = query.Include(customer => customer.Orders);

However this does nothing if you are using SearchExtensions. It does work if you are using just IQueryable (I.E. Entity Framework) or if you add the desired includes before using any SearchExtensions -methods

**Comment by ninjanye** [comment]
Hi @aalho,

Thanks for getting in touch. As you mention, if you run the `.Include` method before `.Search` then to should get the correct results.

I'll look to see if I can implement a fix to this and let you know.

Cheers

**Comment by ninjanye** [comment]
Hi @aalho,

I have just released a new version of [SearchExtensions](https://www.nuget.org/packages/NinjaNye.SearchExtensions/) (version: 1.8.6091.39511).  In this release I have added a fix that addresses this issue.

Thanks again for getting in touch and pointing out this bug.  :+1:
