### ISSUE TITLE
Can't install package into a project that targets .NET Portable

### ISSUE THREAD

**Issue by gwartnes** [ninjanye/SearchExtensions#14]
I'm getting an error when trying to add this NuGet package to my portable class library.

> Could not install package 'NinjaNye.SearchExtensions 2.0.6149.33145'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Are there any plans to include support for targeting other frameworks besides regular .NET?

**Comment by ninjanye** [comment]
Hi @gwartnes,

Thanks for this and the subsequent PR.  I've had a super busy month or 2 so will try and get round to looking at this in the next few days.

Apologies for the delay

**Comment by ninjanye** [comment]
Despite closing your PR, this is still a valid issue and something I hope to add as a priority

**Comment by ninjanye** [comment]
Hi @gwartnes 

SearchExtensions has now been updated and is now build on .NetStandard 1.0.  Hopefully this allows you to use the package.  Be great to hear if this works as it's not somethign I have tried.  My understanding is that .NETStandard should be used to the portable class libraries.

Hope this helps.
Cheers
John
