### ISSUE TITLE
NET Core support

### ISSUE THREAD

**Issue by maximtarasov** [ninjanye/SearchExtensions#18]
Hi!

Your project is very useful and it will be great, if you will introduce NET Core support.

**Comment by ninjanye** [comment]
I completely agree.  This is something I definitely want to do...  Now that the holidays are over, I'll try and get this started

**Comment by ninjanye** [comment]
Hi @maximtarasov 

I begun to look at the work involved in adding .NET Core support and based on the current .Net Standard API (1.6) a fair amount of the code is unsupported and would need to be re-written.  the good news is that all the code is supported in .NET Standard 2.0 so I think I may wait until that is released before adding this.  

Sorry it is going to take longer than i had firts hoped

**Comment by metamet** [comment]
Anyone know of any alternatives for .NET Core? 

I am in the middle of a migration, and trying to iron out all of the incompatibilities here... unfortunately, this is the only one that is in the way at this time.

**Comment by maximtarasov** [comment]
@ninjanye which components are unsupported on NET Core? Can you list them?

**Comment by ninjanye** [comment]
@maximtarasov I'll dig out the report.  From memory it was some reflection stuff and some linq bits.  I'll double check.  If the changes aren't to large, I'll update.

Sorry it's taken a while to get this sorted.

**Comment by ninjanye** [comment]
@maximtarasov @metamet  Good news, I have almost complete the port for .NET Core.  I hope to get a new package out in the next few days.  I'll keep you posted

**Comment by ninjanye** [comment]
@maximtarasov  @metamet IT took longer than anticipated but I have recently released an new version of Search extensions that is now entirely built on `netstandard1.5`

**Comment by ninjanye** [comment]
Resolved as part of  https://github.com/ninjanye/SearchExtensions/commit/38dbff1805dfaeb73b4f9704f498dd48c758d9b6
