### ISSUE TITLE
Could not install package NinjaNye.SearchExtensions 2.1.0 on .NETFramework 4.5

### ISSUE THREAD

**Issue by AbdullahAlimam** [ninjanye/SearchExtensions#20]
Hi I got this error When I try to install it from NuGet:

Could not install package 'NinjaNye.SearchExtensions 2.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ninjanye** [comment]
This has now been addressed and will be fixed in the next release

**Comment by ninjanye** [comment]
The fix for this has now been released and pushed to nuget

https://www.nuget.org/packages/NinjaNye.SearchExtensions/
