### ISSUE TITLE
How can I pass strings as my search properties?

### ISSUE THREAD

**Issue by VictorioBerra** [ninjanye/SearchExtensions#27]
IE:

`dbcontext.entity.Search("LastName").Contains("Billybob")`

This is my current code which is not going so well:

```csharp
foreach (var column in dataTableRequest.columns)
{
    if(column.searchable && !string.IsNullOrWhiteSpace(column.search.value))
    {
        PropertyInfo pinfo = typeof(TViewModel).GetProperty(column.data);

        Expression<Func<TViewModel, string>> propertyExpression = u =>
        (
            column.data
        );

        projectedQuery = projectedQuery
            .Search(propertyExpression)
            .Containing(column.search.value);
    }
}
```

You can probably guess `projectedQuery` is an `IQueryable<T>` where I dont know what `T` is yet.  `dataTableRequest.columns` is an array of simple object eventually ending up with two important properties:

- `dataTableRequest.columns[0].search.value`: The search value
- `dataTableRequest.columns[0].data`: The property of `T` to search against.

Is my approach okay? Should I somehow "lift" the search configuration up to my API Controller action so each entity is configured manually in the action?

**Comment by VictorioBerra** [comment]
## BAD Solution using reflection

```csharp
                    var c = context.Cat
                        .ProjectTo<CatViewModel>();

                    PropertyInfo pinfo = typeof(CatViewModel).GetProperty("Name");

                    c = c
                        .Search(x => (string)pinfo.GetValue(x)) // OR pinfo.GetValue(x).ToString()
                        .Containing("a");
```

As you probably guessed, `(string)pinfo.GetValue(x)) // OR pinfo.GetValue(x).ToString()` can not be converted to SQL and cause everything to be evaluated locally.

I would love to PR this but my knowledge of reflection and expressions are limited, just getting that to work took me half the day and help from StackOverflow.

**Comment by VictorioBerra** [comment]
## Solution

```csharp
Expression<Func<T, string>> BuildStringPropertyExpression<T>(string propertyName) {
    var props = typeof(T).GetProperties();
    var propertyInfo = props.FirstOrDefault(p => string.Equals(p.Name, propertyName, StringComparison.OrdinalIgnoreCase));
    if (propertyInfo == null || propertyInfo.PropertyType != typeof(string)) throw new Exception("invalid property");

    var param = Expression.Parameter(typeof(T), string.Empty);
    var property = Expression.Property(param, propertyInfo);
    return Expression.Lambda<Func<T, string>>(property, param);
}
```

I would love to see this added to the library.

**Comment by ninjanye** [comment]
Hi @VictorioBerra 

Thanks for creating (and solving) the issue.  Apologies for not getting back to you sooner.

If you feel confident enough, I'd happily accept a PR for review.  I would offer to do this myself but work/family is real busy at the moment.   Love the feature though

**Comment by VictorioBerra** [comment]
@ninjanye no worries thanks for replying.

So the above solution is 90% there, the last 10% is recursive property names. est `Customer.Address.City`.

I am bumping up against my knowledge of expression/lambda building. I know these guys https://github.com/StefH/System.Linq.Dynamic.Core have this working somewhere buried in there code [(wiki)](https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions). Maybe I can leverage that library and combine it with yours, or somehow use it in place of yours? Not sure yet.

**Comment by ymolinet** [comment]
up ?

**Comment by VictorioBerra** [comment]
@ymolinet Currently, the solution I provided is 90% there, This issue is up for grabs for a pull request. Theres a ton of information here that can aid you in solving this problem yourself. You may even be able to use the aforementioned System.Linq.Dynamic.Core to build the property accessor automatically. 

@ninjanye Do you have a label for `help-wanted` or `up-for-grabs`?
