### ISSUE TITLE
Core 2.1, EF Core 2.1 "could not be translated and will be evaluated locally"

### ISSUE THREAD

**Issue by VictorioBerra** [ninjanye/SearchExtensions#28]
Not sure if this is related to Core specifically, but I get a console full of errors when I try and use this library related to the Lambda passed to `.Search()` not being able to be translated and instead being evaluated locally. No bueno.

If need be I could upload an example.

**Comment by ninjanye** [comment]
Apologies for not responding sooner. If you could upload an example  that identifies the problem, that'd be great.

**Comment by VictorioBerra** [comment]
I think this was my fault for building a lambda to try and search against a string instead of a property:

```csharp
                    var c = context.Cat
                        .ProjectTo<CatViewModel>();

                    PropertyInfo pinfo = typeof(CatViewModel).GetProperty("Name");

                    c = c
                        .Search(x => pinfo.GetValue(x).ToString())
                        .Containing("a");
```
