### ISSUE TITLE
Allow the searching of child collections

### ISSUE THREAD

**Issue by ninjanye** [ninjanye/SearchExtensions#4]
Investigate the possibility of have SearchExtensions return a parent item if a match is found in a child collection.

A possible example might be: 

> Given I have a collection of Shops, 
> I want to return all shops that stock a product with a `Name` containing "football".

Additionally, support for non strings should be considered:

> Given I have a collection of Shops, 
> I want to return all shops that stock a product with a `Price` greater than 10.

@bzbetty - does this adequately fulfill what you were lookng for?

**Comment by bzbetty** [comment]
That sounds perfect.

**Comment by ninjanye** [comment]
Hi @bzbetty,

I have just released an update to SearchExtensions which partly addresses this issue.  With version 1.7 you can now search child collections.  The reason this is only partly complete is because it is currently only enabled for `IEnumerable` collections meaning that the filtering is done in memory. `IQueryable` is still to come. 

I have created [a blog post explaining how to use the new feature](http://jnye.co/Posts/2045/search-extensions-search-within-child-collections-now-supported-in-v1-7), but in short, with the examples above in mind, you can now do something like the following:

    var result = _shops.SearchChildren(s => s.Products)
                       .With(p => p.Name)
                       .Containing("football");

OR

    var result = _shops.SearchChildren(s => s.Products)
                       .With(p => p.Price)
                       .GreaterThan(10);

I'll be working on supporting `IQueryable` next so that hopefully the server can do the work instead of doing the filtering in memory.

**Comment by bzbetty** [comment]
Awesome! Will try it out as soon as I get the chance.

**Comment by ninjanye** [comment]
Big news!  I have just made a second release which now supports searching on `IQueryable`.  This means that the filtering is all pushed down to the server meaning you only retrieve the matching records.

Blog post to follow

**Comment by bzbetty** [comment]
you are too awesome!

**Comment by bzbetty** [comment]
Is it possible to use a Search and a SearchChildren at the same time?  It
looks like chaining them in C# will perform a AND query instead of an OR
query?

eg

SELECT [Extent1].[Id] AS [Id]
  -- Additional columns --
FROM [dbo].[Shops] AS [Extent1]
WHERE
 [Extent1].Name like '%ball%'
or
EXISTS (
  SELECT 1 AS [C1]
  FROM [dbo].[Products] AS [Extent2]
  WHERE ([Extent1].[Id] = [Extent2].[Shop_Id])
    AND ([Extent2].[Name] LIKE N'%ball%')
)

**Comment by ninjanye** [comment]
Can you post the code you are using to try this? I think it should be possible with the current code base

**Comment by bzbetty** [comment]
Context.Invoices
    .Search(invoice => invoice.Description).ContainingAll(searchTerms)
    .SearchChildren(invoice => invoice.Client).With(client =>
client.Name).ContainingAll(searchTerms)

also tried

Context.Invoices
    .Search(invoice => invoice.Description)
    .SearchChildren(invoice => invoice.Client).With(client =>
client.Name).ContainingAll(searchTerms)

**Comment by ninjanye** [comment]
Hmmm, I would have thought the first option would have done the trick. I'll be on the train to work in a bit so will investigate. I'm pretty sure it should be possible though

**Comment by bzbetty** [comment]
it works but it requires both the invoice description and client name to
contain all the search terms, I was wanting to be able to do one or the
other.  Unfortunately i suspect that would require large changes.

**Comment by ninjanye** [comment]
Ah, I see, apologies.  Funnily enough, I have just replied to issue #6 asking for precisely the same thing.

As a workaround, you could potentially run them as 2 separate queries (which I know is not ideal).  What this does mean is that you only have to perform the second query if the first doesn't return any results.  Something like:

    var description = Context.Invoices.Search(invoice => invoice.Description)
                                      .ContainingAll(searchTerms);

    var client = Context.Invoices.SearchChildren(invoice => invoice.Client)
.With(client =>
client.Name).ContainingAll(searchTerms)

**Comment by bzbetty** [comment]
it's not actually a big deal in my case as normally the user knows which
field contains the data anyway so I've put 2 buttons in the UI.   2
searches + a union of some kind would work fairly well too.  Cheers for the
help.

**Comment by ninjanye** [comment]
No probs, I will look at how we can maybe have an indicator in the searches to allow for an OR search across search types as it would clearly be useful since you and @sunflowerlab have both mentioned it.
