### ISSUE TITLE
Containing search also adds StartsWith and EndsWith to expression

### ISSUE THREAD

**Issue by AVee** [ninjanye/SearchExtensions#5]
After upgrading to 1.6 I noticed Containing() adds not just the expression for .Contains() but also for StartsWith() and EndsWith(). This is rather painfull for search performance.
I think the cause is in QueryableContainsExpressionBuilder line 23-27, added in https://github.com/ninjanye/SearchExtensions/commit/1bdfb74cdb88476c60eec4a6514fd959982860c1

**Comment by ninjanye** [comment]
Hi @AVee,  

Thanks for noticing this.  I have now fixed (ba8a5e4) this in the latest release. 

:+1:  for raising an issue.
