### ISSUE TITLE
Searching various tables with composite keys

### ISSUE THREAD

**Issue by smartmeter** [ninjanye/SearchExtensions#7]
Hi. thanks for the lib, I was trying it and saw searches across properties but did not list any help on the entity collections/tables. 

I have 4 tables with that contain composite Keys made of a *string** and a **SerialNo**    

Since the search **Key**  for e.g.  `AX903200287  or  Uz09238744222344` is long (and no human friendly the user cannot differentiate if it belongs to a Parts Table or Services Table or Chem/Materials tables.)

Can you please show me 

*     how can I find hits for the entire search strings in those tables/entities?
*     how can I fragment the search to begin with the numbers segment only?

thanks

**Comment by ninjanye** [comment]
Hi @smartmeter,

If I understand your problem correctly, you achieve this providing your results have access to the related tables.  For instance

    context.Data.SearchChildren(x => x.RelatedTable).With(y => y.Key).EqualTo("AX903200287");

You can find more details on [this blog post](http://jnye.co/Posts/2046/search-extensions-child-collection-search-support-and-over-3000-downloads) which I hope help to explain
